//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:55:05 PM EET 
//


package ru.dazzled.ecb.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.ecb.vocabulary._2002_08_01.eurofxref package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cube_QNAME = new QName("http://www.ecb.int/vocabulary/2002-08-01/eurofxref", "Cube");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.ecb.vocabulary._2002_08_01.eurofxref
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CubeType }
     * 
     */
    public CubeType createCubeType() {
        return new CubeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CubeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ecb.int/vocabulary/2002-08-01/eurofxref", name = "Cube")
    public JAXBElement<CubeType> createCube(CubeType value) {
        return new JAXBElement<CubeType>(_Cube_QNAME, CubeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CubeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ecb.int/vocabulary/2002-08-01/eurofxref", name = "Cube", scope = CubeType.class)
    public JAXBElement<CubeType> createCubeTypeCube(CubeType value) {
        return new JAXBElement<CubeType>(_Cube_QNAME, CubeType.class, CubeType.class, value);
    }

}
