//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 03:55:05 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ecb.int/vocabulary/2002-08-01/eurofxref", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.dazzled.ecb.jaxb;
